### ISSUE TITLE
Training procedure

### ISSUE THREAD

**Issue by pengsongyou** [lwwu2/diver#1]
Hi @lwwu2,

First of all, thanks so much for the great work and for making the code available!

I was trying to train a DIVeR on the drums sequence from nerf-synthetic dataset. The readme for the training is unclear to me and I got some very weird results. Below is my way of training:

1. Train an implicit model in the coarse level (by replacing `configs/config.py` with `configs/nerf_synthetic_coarse.py`), and run `python train.py --experiment_name=drums --gpus=1 --resume`
2. Prune this trained coarse model via `python prune.py --checkpoint_path=logs/drums/version_3/checkpoints`
3. Continue training on the fine level (by replacing `configs/config.py` with `configs/nerf_synthetic_fine.py`), and run `python train.py --experiment_name=drums --gpus=1 --resume`.

Right after step 3, I obtain something very strange already, as shown here: https://imgur.com/a/mz6ILXq. I wonder which step I made a mistake? Also, could you please make the training step more clear so we know how to really reproduce the results shown in the paper? 

Thanks so much in advance!

Best,
Songyou

**Comment by lwwu2** [comment]
Hi @pengsongyou,

Thanks for the interest in our work and sorry for the confusion.

The training on the fine level does not resume from the coarse level. So either `--resume` flag should not be set or the `experiment_name` should be named differently for fine level training. In our setup, we set `experiment_name` differently for each stage (coarse, implicit, implicit-explicit) and only use `--resume` flag if the training at certain stage is interrupted. Also, `checkpoints` and `logs` should be two independent folders, which may vary if the pytorch-lighting version is different.

Meanwhile, the `prune.py` script would not extract the occupancy map if it found an old one under the given folder. We just changed the code to update the occupancy map when the scripted is recalled.

In the newest README, we have included a more detailed example on how to reproduce the drums scene under the **Reproduction** section. Let us know if you have more questions.

Best,
Liwen
