### ISSUE TITLE
Integration of trilinear interpolation

### ISSUE THREAD

**Issue by Frivas97** [lwwu2/diver#3]
Hi! 

First of all, congrats for your work! I really enjoyed reading the paper ang going through the code (which is quite understandable). I have a question about how you integrate the trilinear interpolation of the features for each voxel. In the paper, you obtain the following equation:
![imagen](https://user-images.githubusercontent.com/98962882/152360191-b9b0073a-7311-443d-a062-5dc170842e82.png)

I do not see how you finally solve the integral and how you implemented. I undestand the implementation is the following one on integrator.py:

`

    A = P.sum(0).prod(0)/12+(P.prod(1).sum(0))/6
    X = F[1] - F[0]
    X = X[0] - X[1]
    X = X[0] - X[1]
    feature = A[:,None]*X
    
    P_roll = P[:,[1,2,0]]
    # 3xBxM
    B = (P*P_roll).sum(0)/3+(P*P_roll[[1,0]]).sum(0)/6
    # 3xBxMxC
    Y = F[0,0,0,None]-F[[0,0,1],[1,1,0],0]\
       -F[[0,1,0],0,[1,0,1]]+F[[0,1,1],[1,1,0],[1,0,1]]
    feature = feature + torch.einsum('dk,dkc->kc',B,Y)
    
    # 3xBxM
    C = P.sum(0)/2
    # 3xBxMxC
    Z = F[[0,0,1],[0,1,0],[1,0,0]]-F[0,0,0,None]
    feature = feature + torch.einsum('dk,dkc->kc',C,Z)
    feature = feature + F[0,0,0]
 `

What is the actual formula you are applying here? Do you have some derivation of the integral and this implementation?

Thanks in advance!

**Comment by lwwu2** [comment]
Hi,

Thanks for your interest in our work. 

The integrations of trilinear interpolation weights are essentially the integrations of certain polynomials of t, but the formula is too long to be written down. The process of solving the integral is equivalent to the following python script: 
```
import sympy as spy
# start and end point
x0,y0,z0 = spy.symbols('x0 y0 z0')
x1,y1,z1 = spy.symbols('x1 y1 z1')

# corner features
f000,f001,f010,f011,f100,f101,f110,f111\
         = spy.symbols('f1 f2 f3 f4 f5 f6 f7 f8')

# ray parameterization 
t = spy.symbols('t')
lerp = lambda p0,p1: p0*(1-t) + p1*t
x,y,z = lerp(x0,x1),lerp(y0,y1),lerp(z0,z1)

# trilinear interpolation
feature = f000*(1-x)*(1-y)*(1-z) + f001*x*(1-y)*(1-z)\
        + f010*(1-x)*y*(1-z) + f011*x*y*(1-z)\
        + f100*(1-x)*(1-y)*z + f101*x*(1-y)*z\
        + f110*(1-x)*y*z + f111*x*y*z

# integration 
integral = spy.integrate(feature,(t,0,1))
integral
```
The code you mentioned is a factorization of the formula to make it easy to be evaluated in pytorch. In our CUDA implementation, we used another simpler factorization, which will be provided after the revision of the paper:
![formula](https://user-images.githubusercontent.com/93700419/152434286-7f5a789d-ab82-4454-aab8-e13c0bdd2916.png)

Let us know if you have more questions.

**Comment by Frivas97** [comment]
Hi! Sorry for the late response, your answer was really helpful, thanks a lot!. I have another question relating the features:

In this figure, you show the feature are activated before being passed to the MLP 
![imagen](https://user-images.githubusercontent.com/98962882/182182494-d3046a02-72bd-49c8-9110-500a567a72f5.png)

However, I could not find that in the code. Is that a typpo? Are I missing something?

Thanks for yor help

**Comment by Frivas97** [comment]
Sorry for the late response. Thanks a lot for your help, it was really helpful!
