### ISSUE TITLE
Understanding the pre-multiply first linear

### ISSUE THREAD

**Issue by doramasma** [lwwu2/diver#6]
Hi, thank you very much for your great work!
Currently, I am using a modified diver model for one of my research.  In this model, the size of the first layer is different (bigger), so I would like to know in detail how the pre-multiplication logic works, to see if I can premultiply my first layer with the features. 

To the best of my knowledge, we keep the layer bias 0 "new_weight['weightin'][:,0]," and then perform the premultiplication to the features. Why we perform the transpose? "features = (features@new_weight['weightin'][:,1:].T).contiguous()", in this case, the shapes of the weights are 32x32, what happens if i change the size of my layers? 

```
params = torch.cat([
                new_weight['weightin'][:,0],
                new_weight['weight0'].T.reshape(-1),
                new_weight['weight1'].reshape(-1),
                w2.T.reshape(-1),
                new_weight['weight3'].T.reshape(-1),
                torch.zeros(28),
],0).contiguous() 

# store feature vectors in an 1d array
voxels = new_weight['voxels'].coalesce()
N = voxels.shape[0]-1
idxs = voxels.indices()
features = voxels.values()

# pre-multiply first linear layer to feature vector for diver32 model
if voxel_dim == 32:
    features = (features@new_weight['weightin'][:,1:].T).contiguous()
```

Thanks :)

**Comment by lwwu2** [comment]
Hi, thank you for your interest in our work.
The ```features``` here is a stack of feature vectors in shape ```number_of_features x dim_in``` and the weight is of shape ``` dim_out x dim_in ```. To multiply each feature vectors by the weight and store the stacked output features in shape ``` number_of_features x dim_out ```, it is equivalent to multiply the stacked features with the transpose of the weight matrix (``` dim_in x dim_out ```).

The pre-multiplication will still work for different layer size but bigger size features might take more storage and loading time.

**Comment by doramasma** [comment]
Thank you very much, it has been very useful
