### ISSUE TITLE
Reproducing results and evaluating released pretrained models

### ISSUE THREAD

**Issue by mikacuy** [lwwu2/diver#9]
Hi,

Thank you for your great work! I'm Mika, a fourth year PhD student at Stanford. (I sent an email but it seemed to have bounced back).

We are currently trying to run your released pretrained models as well as reproduce the results in the paper, but we are experiencing some issues when running the [released github code](https://github.com/lwwu2/diver) and are hoping you can help us out. (It is time sensitive since we are rushing for deadline, so we would greatly appreciate it if you can answer our questions soon.).

Specifically, we are trying to reproduce the results on the nerf_synthetic dataset, and here are our questions:

1. Which configuration file in the config/ should we use to reproduce the published results? 
2. Which set of weights correspond to the fine model that can be directly used with the evaluation script (eval.py) to evaluate the released pretrained models? We tried the three folders from [your google drive](https://drive.google.com/drive/folders/1iaQ-PIS7ydpoNj2OToLgAi-3lCyJG4MN), and we didn't seem to get any of them to run (we also changed config.py to nerf_synthetic_fine).
3. Would you be able to send us a sample evaluation script to  reproduce the published results using the downloadable weights on nerf synthetic?

Some of the things that we tried but didn't need to work are:

- When using the weights from the [nerf_synthetic folder](https://drive.google.com/drive/folders/1iaQ-PIS7ydpoNj2OToLgAi-3lCyJG4MN), the eval script errored out due to "weights' voxel mask size is [64, 64, 64]", mismatching with the fine model's configuration.
- When using the weights from the [nerf_synthetic256 folder](https://drive.google.com/drive/folders/1iaQ-PIS7ydpoNj2OToLgAi-3lCyJG4MN), the eval script errored because it didn't have voxels in its set of weights.

Thank you in advance for your help and response!

Best,
Mika

**Comment by mikacuy** [comment]
Resolved via email response. Thank you very much for the swift reply!

**Comment by nfyfamr** [comment]
Hi, I have the exact same question here. Can I be shared the answer as well? @mikacuy @lwwu2 I appreciate it!

**Comment by lwwu2** [comment]
Hi,

The results can be reproduced by following reproduction section https://github.com/lwwu2/diver#reproduction. Basically, config file needs to be changed for each stage of optimization.

nerf_synthetic folder has the weight that can be loaded into the eval.py script (using nerf_synthetic_fine.py) and nerf_synthetic256/128 is the weight for eval_rt.py
I stored the voxel_mask with 64 resolution for chair scene by mistake, which I think can be resolved by changing 'hparams.mask_scale = 1' to 'hparams.mask_scale = 0.25' in https://github.com/lwwu2/diver/blob/78684e5e5004896be9bc1cc3eaa01bb94f02c042/eval.py#L45C9-L45C31. Weights for the other scenes should be fine.

Let me know if you have any other questions.

**Comment by nfyfamr** [comment]
@lwwu2 Thanks for your invaluable comment! Now I understand it!
